/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/homestead.glb 
Author: EdwinRC (https://sketchfab.com/Edwin3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-farm-v2-0e91a96ca6ee44569cf94972e30b5be4
Title: Low Poly Farm V2
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, animated } from '@react-spring/three'

interface AnimatedGroupProps {
  children: React.ReactNode;
  stage: number;
  currentStage: number;
  dropHeight?: number;
}

function AnimatedGroup({ children, stage, currentStage, dropHeight = 10 }: AnimatedGroupProps) {
  const active = currentStage >= stage;
  const [visible, setVisible] = useState(active);

  if (active && !visible) {
    setVisible(true);
  }

  const { z } = useSpring({
    z: active ? 0 : dropHeight,
    from: { z: dropHeight },
    config: { mass: 5, tension: 40, friction: 2, clamp: true },
    onChange: ({ value }) => {
      // In local coordinates, Z is up because parent is rotated -Math.PI / 2 on X
      if (!active && value.z >= dropHeight - 0.05) {
        setVisible(false);
      }
    },
  });

  return (
    <animated.group position={z.to((val) => [0, 0, val]) as any} visible={visible}>
      {children}
    </animated.group>
  );
}

export function Homestead({ currentStage, ...props }: React.ComponentPropsWithoutRef<'group'> & { currentStage: number }) {
  const { nodes, materials } = useGLTF('/homestead.glb') as any
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* Stage 1: Base Land and Ground Features */}
        <AnimatedGroup stage={1} currentStage={currentStage} dropHeight={0}>
          <mesh geometry={nodes.Plane002_0.geometry} material={materials.material_12} position={[0, 0, 0.397]} scale={27.971} />
          <mesh geometry={nodes.Plane_0.geometry} material={materials.material_5} position={[11.668, -0.832, -0.036]} rotation={[0, 0, 1.257]} scale={0.697} />
          <mesh geometry={nodes.Plane004_0.geometry} material={materials.material_1} position={[-1.193, -2.663, 1.307]} rotation={[0, 0, -1.605]} scale={0.266} />
          <mesh geometry={nodes.Plane007_0.geometry} material={materials.material} position={[2.934, -3.629, 2.253]} rotation={[-1.555, 0.633, -0.974]} scale={0.048} />
          <mesh geometry={nodes.Plane008_0.geometry} material={materials.material} position={[12.773, 10.98, 2.095]} rotation={[-1.346, -1.198, -0.769]} scale={0.048} />
          <mesh geometry={nodes.Plane006_0.geometry} material={materials.material} position={[19.13, 13.384, 2.096]} rotation={[1.582, -0.408, 2.158]} scale={0.048} />
        </AnimatedGroup>

        {/* Stage 2: Main Buildings and Structures */}
        <AnimatedGroup stage={2} currentStage={currentStage}>
          <mesh geometry={nodes.Cube013_0.geometry} material={materials.material_13} position={[0.855, 18.169, 3.04]} rotation={[0, 0, Math.PI / 2]} scale={0.958} />
          <mesh geometry={nodes.Cube011_0.geometry} material={materials.material_14} position={[5.607, 12.989, 4.098]} rotation={[-0.02, -0.01, 0.822]} scale={[0.255, 0.255, 0.197]} />
          <mesh geometry={nodes.Cylinder000_0.geometry} material={materials.material_2} position={[3.86, 18.232, -0.045]} rotation={[0.113, -0.109, 0.605]} scale={0.128} />
          <mesh geometry={nodes.Cylinder001_0.geometry} material={materials.material_2} position={[5.179, 19.738, 0.222]} rotation={[0, 0, -1.191]} scale={0.128} />
          <mesh geometry={nodes.Cube009_0.geometry} material={materials.material_10} position={[15.083, -1.572, 0.514]} />
          <mesh geometry={nodes.Cube010_0.geometry} material={materials.material_9} position={[7.771, -1.572, 0.335]} />
        </AnimatedGroup>

        {/* Stage 3: Details, Trees, Fences, etc. */}
        <AnimatedGroup stage={3} currentStage={currentStage}>
          <mesh geometry={nodes.Plane000_0.geometry} material={materials.material_11} position={[5.072, 23.401, 11.792]} rotation={[-0.482, 0.203, 1.203]} scale={0.389} />
          <mesh geometry={nodes.Text001_0.geometry} material={materials.material_8} position={[20.013, 7.23, 5.606]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Cube014_0.geometry} material={materials.material_7} position={[-5.171, 9.111, 15.446]} scale={0.098} />
          <mesh geometry={nodes.Plane005_0.geometry} material={materials.material_6} position={[-11.175, 25.238, 5.745]} rotation={[Math.PI / 2, -1.002, 0]} scale={[1.304, 2.024, 1.304]} />
          <mesh geometry={nodes.Sphere001_0.geometry} material={materials.material_4} position={[12.24, 20.064, 0.699]} rotation={[-Math.PI / 2, 0, -1.379]} scale={1.042} />
          <mesh geometry={nodes.Cube001_0.geometry} material={materials.material_3} position={[1.979, 1.59, 0.531]} scale={[0.555, 0.769, 0.555]} />
          <mesh geometry={nodes.Cube000_0.geometry} material={materials.material_3} position={[2.229, -0.264, 0.531]} rotation={[0, 0, -3.007]} scale={[0.555, 0.769, 0.555]} />
          <mesh geometry={nodes.Cube002_0.geometry} material={materials.material_3} position={[2.143, 0.707, 1.629]} rotation={[Math.PI, 0, 0.135]} scale={[0.555, 0.769, 0.555]} />
          <mesh geometry={nodes.Plane001_0.geometry} material={materials.material_1} position={[16.64, 17.942, 0.928]} rotation={[0.14, -0.044, -0.524]} scale={0.454} />
          <mesh geometry={nodes.Plane003_0.geometry} material={materials.material_1} position={[18.719, 18.328, 0.938]} rotation={[0, 0, -2.858]} scale={0.454} />
        </AnimatedGroup>
      </group>
    </group>
  )
}

useGLTF.preload('/homestead.glb')
